all: 
	@gcc *.c -Wall -pedantic-errors -o programa

run:
	echo ../casos-testes/entradas/entrada01.txt ../output/saida01heur.txt | ./programa 
	echo ../casos-testes/entradas/entrada02.txt ../output/saida02heur.txt | ./programa 
	echo ../casos-testes/entradas/entrada03.txt ../output/saida03heur.txt | ./programa 
	echo ../casos-testes/entradas/entrada04.txt ../output/saida04heur.txt | ./programa 
	echo ../casos-testes/entradas/entrada05.txt ../output/saida05heur.txt | ./programa 
